<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yutaka" name="com.sqa.ao.assertTests.AssertTests" tests="9" failures="2" timestamp="31 Oct 2015 18:01:22 GMT" time="0.026" errors="0">
  <testcase name="testAssertEqualsNewString" time="0.001" classname="com.sqa.ao.assertTests.AssertTests"/>
  <testcase name="testAssertNotSame" time="0.002" classname="com.sqa.ao.assertTests.AssertTests">
    <failure type="java.lang.AssertionError" message="str1 == str2 expected not same [my str] but found [my str]">
      <![CDATA[java.lang.AssertionError: str1 == str2 expected not same [my str] but found [my str]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failSame(Assert.java:484)
	at org.testng.Assert.assertNotSame(Assert.java:465)
	at com.sqa.ao.assertTests.AssertTests.testAssertNotSame(AssertTests.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- testAssertNotSame -->
  <testcase name="testAssertSameNewString" time="0.000" classname="com.sqa.ao.assertTests.AssertTests">
    <failure type="java.lang.AssertionError" message="str1 == str2 expected [my str] but found [my str]">
      <![CDATA[java.lang.AssertionError: str1 == str2 expected [my str] but found [my str]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:492)
	at org.testng.Assert.assertSame(Assert.java:443)
	at com.sqa.ao.assertTests.AssertTests.testAssertSameNewString(AssertTests.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- testAssertSameNewString -->
  <testcase name="testAssertSame" time="0.001" classname="com.sqa.ao.assertTests.AssertTests"/>
  <testcase name="testAssertNotNull" time="0.001" classname="com.sqa.ao.assertTests.AssertTests"/>
  <testcase name="testAssertEquals" time="0.000" classname="com.sqa.ao.assertTests.AssertTests"/>
  <testcase name="testAssertNotSameNewString" time="0.001" classname="com.sqa.ao.assertTests.AssertTests"/>
  <testcase name="assertFalse" time="0.019" classname="com.sqa.ao.assertTests.AssertTests"/>
  <testcase name="assertTrue" time="0.001" classname="com.sqa.ao.assertTests.AssertTests"/>
</testsuite> <!-- com.sqa.ao.assertTests.AssertTests -->
